services:
  mysql-db:
    image: mysql:8.0
    container_name: reservation_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u$$MYSQL_USER -p$$MYSQL_PASSWORD"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build: .
    container_name: reservation_api
    restart: always
    depends_on:
      mysql-db:
        condition: service_healthy
    env_file: .env
    environment:
      DB_URL: jdbc:mysql://mysql-db:3306/${DB_NAME}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    ports:
      - "8080:8080"

volumes:
  mysql_data:
